services:
  # --- THEHIVE & CORTEX STACK ---
  thehive:
    image: strangebee/thehive:5.2
    restart: unless-stopped
    depends_on:
      - cassandra
      - elasticsearch  # <-- DIPERBARUI
      - minio
      - cortex
    mem_limit: 2g
    ports:
      - "0.0.0.0:9000:9000"
    environment:
      - JVM_OPTS="-Xms1024M -Xmx1024M"
    command:
      - --secret
      - "lab123456789"
      - --cql-hostnames
      - "cassandra"
      - --index-backend
      - "elasticsearch"
      - "--es-hostnames"
      - "elasticsearch" # <-- DIPERBARUI
      - "--s3-endpoint"
      - "http://minio:9002"
      - "--s3-access-key"
      - "minioadmin"
      - "--s3-secret-key"
      - "minioadmin"
      - "--s3-use-path-access-style"
      - "--cortex-port"
      - "9001"
      - "--cortex-keys"
      - "JX+ksmITFvk2S3NRgqjcLJNwRg+3MHBF"
    volumes:
      - thehivedata:/etc/thehive/application.conf
    networks:
      - SOC_NET

  cassandra:
    image: 'cassandra:4'
    restart: unless-stopped

    ports:
      - "0.0.0.0:9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TheHive
    volumes:
      - cassandradata:/var/lib/cassandra
    networks:
      - SOC_NET

  # NAMA SERVICE DAN CONTAINER DIUBAH DI SINI
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    restart: unless-stopped
    mem_limit: 2g
    ports:
      - "0.0.0.0:9201:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.name=hive
      - http.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g" # Direkomendasikan 1g
    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data
    networks:
      - SOC_NET

  minio:
    image: quay.io/minio/minio
    restart: unless-stopped
    mem_limit: 512m
    command: ["minio", "server", "/data", "--console-address",":9002"]
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "0.0.0.0:9002:9002"
    volumes:
      - "miniodata:/data"
    networks:
      - SOC_NET

  cortex:
    image: thehiveproject/cortex:3.6.1-1 # <-- Menggunakan versi spesifik, bukan 'latest'
    restart: unless-stopped
    depends_on:
      - elasticsearch
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/siem-admin/thehive_cortex/cortex/cortex-jobs:/tmp/cortex-jobs
    ports:
      - "0.0.0.0:9001:9001"
    networks:
      - SOC_NET

volumes:
  # TheHive & Cortex Volumes
  miniodata:
  cassandradata:
  elasticsearchdata:
  thehivedata:

networks:
  SOC_NET:
    driver: bridge
